- name: Add Logstash repo key
  rpm_key: key="http://packages.elastic.co/GPG-KEY-elasticsearch" state=present

- name: Enable Logstash repository
  template: src=logstash_repo.j2 dest=/etc/yum.repos.d/logstash.repo

- name: Install Logstash from repository
  yum: name={{ item }} state=present update_cache=yes
  with_items:
   - logstash

- include: logstash_conf.yml
- include: geolite.yml