- name: Add Logstash repo key
  rpm_key: key="https://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

- name: Enable Elasticsearch repository
  template: src=es_repo.j2 dest=/etc/yum.repos.d/elasticsearch.repo

- name: Install Elasticsearch from repository
  yum: name={{ item }} state=present update_cache=yes
  with_items:
   - elasticsearch
  notify:
   - restart elasticsearch

- name: ensure elasticsearch is running
  service: name=elasticsearch state=started enabled=yes

- include: es_config.yml
